Repository bitbitedev/OpenLogLib, pull requests merged in 2022-07, with the labels that each got.

#29 Closes #20
  src/main/java/dev/bitbite/logging/Log.java
  src/main/java/dev/bitbite/logging/log/ConsoleLog.java
  src/main/java/dev/bitbite/logging/log/FileLog.java
Labels: enhancement

#30 Closes 21
  src/main/java/module-info.java
Labels: enhancement

#33 Closes #22
  src/main/java/dev/bitbite/logging/Log.java
Labels: bug

#35 Fixes #28
  src/main/java/dev/bitbite/logging/Log.java
  src/main/java/dev/bitbite/logging/log/FileLog.java
Labels: bug

#37 Maven credentials from Environment variables (#36)
  build.gradle
Labels: bug, enhancement
